"""Pure-Python ctmm 1.3.0 port modules.

Each submodule corresponds to one original ctmm R source file. The mapping is
kept as documentation for parity work; runtime code does not call R.
"""

from __future__ import annotations

R_TO_PY_MODULE: dict[str, str] = {
    '1.R': 'r_1.py',
    'QP.R': 'QP.py',
    'acf.R': 'acf.py',
    'aicc.R': 'aicc.py',
    'animate.R': 'animate.py',
    'anonymize.R': 'anonymize.py',
    'bandwidth.R': 'bandwidth.py',
    'cde.R': 'cde.py',
    'change.point.R': 'change_point.py',
    'circle.R': 'circle.py',
    'cluster.R': 'cluster.py',
    'color.R': 'color.py',
    'compass.R': 'compass.py',
    'convex.R': 'convex.py',
    'corridor.R': 'corridor.py',
    'covm.R': 'covm.py',
    'crayon.R': 'crayon.py',
    'ctmm.R': 'ctmm.py',
    'ctpm.R': 'ctpm.py',
    'cv.R': 'cv.py',
    'dexp.R': 'dexp.py',
    'diagnostic.R': 'diagnostic.py',
    'diff.R': 'diff.py',
    'diffusion.R': 'diffusion.py',
    'distance.R': 'distance.py',
    'dt.R': 'dt.py',
    'emulate.R': 'emulate.py',
    'encounter.R': 'encounter.py',
    'export.R': 'export.py',
    'extent.R': 'extent.py',
    'fit.R': 'fit.py',
    'funnel.R': 'funnel.py',
    'gaussian.R': 'gaussian.py',
    'generic.R': 'generic.py',
    'grid.R': 'grid.py',
    'homerange.R': 'homerange.py',
    'int.R': 'int_r.py',
    'kalman.R': 'kalman.py',
    'kde.R': 'kde.py',
    'krige.R': 'krige.py',
    'lasso.R': 'lasso.py',
    'likelihood.R': 'likelihood.py',
    'log.R': 'log.py',
    'log.ctmm.R': 'log_ctmm.py',
    'mag.R': 'mag.py',
    'math.R': 'math.py',
    'matrix.R': 'matrix.py',
    'mean.R': 'mean.py',
    'mean.UD.R': 'mean_UD.py',
    'mean.ctmm.R': 'mean_ctmm.py',
    'mean.mu.R': 'mean_mu.py',
    'median.R': 'median.py',
    'meta.chisq.R': 'meta_chisq.py',
    'meta.normal.R': 'meta_normal.py',
    'modes.R': 'modes.py',
    'npr.R': 'npr.py',
    'nsv.R': 'nsv.py',
    'numDeriv.R': 'numDeriv.py',
    'occurrence.R': 'occurrence.py',
    'optim.R': 'optim.py',
    'outlier.R': 'outlier.py',
    'overlap.R': 'overlap.py',
    'parallel.R': 'parallel.py',
    'parameters.R': 'parameters.py',
    'periodogram.R': 'periodogram.py',
    'plot.telemetry.R': 'plot_telemetry.py',
    'plot.variogram.R': 'plot_variogram.py',
    'plot3d.R': 'plot3d.py',
    'population.R': 'population.py',
    'projection.R': 'projection.py',
    'quant.R': 'quant.py',
    'ridge.R': 'ridge.py',
    'rsf.R': 'rsf.py',
    'rsf.select.R': 'rsf_select.py',
    'sdm.R': 'sdm.py',
    'select.R': 'select.py',
    'series.R': 'series.py',
    'sigfig.R': 'sigfig.py',
    'speed.R': 'speed.py',
    'speeds.R': 'speeds.py',
    'split.R': 'split.py',
    'stats.R': 'stats.py',
    'str.R': 'str_r.py',
    'suitability.R': 'suitability.py',
    'summary.ctmm.R': 'summary_ctmm.py',
    'telemetry.R': 'telemetry.py',
    'tensor.R': 'tensor.py',
    'time.R': 'time.py',
    'transition.R': 'transition.py',
    'ts.plot.R': 'ts_plot.py',
    'uere.R': 'uere.py',
    'units.R': 'units.py',
    'variogram.R': 'variogram.py',
    'variogram.fit.R': 'variogram_fit.py',
    'variogram.test.R': 'variogram_test.py',
}

__all__ = [
    "R_TO_PY_MODULE",
]
